# Site settings
title: Keymetrics Documentation
email: contact@keymetrics.io
description: > # this means to ignore newlines until "baseurl:"
  Keymetrics, a powerful networked software allowing you to supervize applications.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://docs.keymetrics.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

sass:
  sass_dir: _sass

# Build settings

exclude: ['node_modules', 'docs/intro.md']

redcarpet:
  extensions: ['tables', 'no_intra_emphasis', 'autolink']

permalink: /blog/:year/:month/:day/:title
paginate: 1

gems: ['jekyll-lunr-js-search']

lunr_search:
  js_dir: "../scripts"
